




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%Regresion

\section{Modelos de Regresion}\label{regresion}

<<getData, echo=FALSE>>=
# Cargar archivo ----

# NO OLVIDAR set working directory
filename="colombia.csv"
colb=read.csv(filename, stringsAsFactors = FALSE)

# que variables y tipo
#str(colb)
@

En conclusión, vemos los modelos propuestos. Primero sin la poblacion restante como variable independiente, y luego con está. Los resultados se muestran en la Tabla \ref{regresiones} de la página \pageref{regresiones}.

<<regresiones, echo=FALSE>>=
# Veamos los modelos propuestos. 
# Primero sin poblacion resto, luego con esa:

LinRegA = lm(IDH ~ ., data = colb[,c(1,7)])
LinRegB = lm(IDH ~ ., data = colb[,c(1,7:8)])

@


<<regresionesPlot,results=tex, echo=false>>=
stargazer(LinRegA,LinRegB,
          title = "Modelos de Regresión", 
          label = "regresiones")
@


\endinput